In [ ]:
data = [10, 20, 30, 40, 50]

In [ ]:
print(data[0])
print(data[2])

In [5]:
1print(10>5)

True

In [7]:
print(10<5)

False

In [8]:
import numpy as np

data = np.array([10,20,30,40,50])

In [9]:
data > 20

array([False, False,  True,  True,  True])

In [10]:
data[data > 20]

array([30, 40, 50])

In [17]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

condition = data > 20
print(condition)

[False False  True  True  True]

In [21]:
data = np.array([10, 20, 30, 40, 50])

condition = data > 20

result = data[condition]

result = data[data > 20]

print(result)

[30 40 50]

In [22]:
data = np.array([10, 20, 30, 40, 50])
data[data >= 30]

array([30, 40, 50])

In [23]:
data[data < 30]

array([10, 20])

In [24]:
data[data == 30]

array([30])

In [25]:
data[data != 30]

array([10, 20, 40, 50])

In [26]:
data = np.array([10, 20, 30, 40, 50, 60])

data[(data > 20) & (data < 50)]

array([30, 40])

In [27]:
data[(data >= 20) & (data <= 50)]

array([20, 30, 40, 50])

In [28]:
data >= 20

array([False,  True,  True,  True,  True,  True])

In [29]:
data <= 50

array([ True,  True,  True,  True,  True, False])

In [30]:
data[(data < 20) | (data > 50)]

array([10, 60])

In [32]:
data = np.array([10, 20, 30, 40, 50])

data[data >= 30] = 0
print(data)

[10 20  0  0  0]

In [33]:
data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

In [34]:
data > 30

array([[False, False],
       [False,  True],
       [ True,  True]])

In [35]:
data[data > 30]

array([40, 50, 60])

In [36]:
fish_length = np.array([
    25.4, 26.3, 26.5,
    29.0, 30.0, 31.0,
    35.0, 40.0
])

In [37]:
fish_length[fish_length >= 30]

array([30., 31., 35., 40.])

In [50]:
fish_length >= 30

array([False, False, False, False,  True,  True,  True,  True])

In [38]:
fish_target = np.array([
    1, 1, 1, 1,
    0, 0, 0
])

In [39]:
fish_target == 1

array([ True,  True,  True,  True, False, False, False])

In [40]:
fish_target[fish_target == 1]

array([1, 1, 1, 1])

In [41]:
data = [10, 20, 30, 40, 50]

In [42]:
data > 20

TypeError: '>' not supported between instances of 'list' and 'int'

In [44]:
result = [x for x in data if x > 20]
print(result)

[30, 40, 50]

In [45]:
data = np.array([10, 20, 30, 40, 50])

data[data > 20]

array([30, 40, 50])

In [46]:
data = np.array([10, 20, 30, 40, 50])

data[data > 20]

array([30, 40, 50])

In [47]:
import pandas as pd

df = pd.DataFrame({
    "name": ["홍길동", "김철수", "이영희", "박민수"],
    "age": [18, 25, 17, 30]
})

In [48]:
df

  name  age
0  홍길동   18
1  김철수   25
2  이영희   17
3  박민수   30

In [49]:
df[df["age"] >= 20]

  name  age
1  김철수   25
3  박민수   30