In [3]:
import pandas as pd

df = pd.DataFrame({
    'name': ['홍길동', '김철수', '이영희'],
    'age': [20, 25, 23],
    'score': [90, 80, 95]
})

# print(df)
df

  name  age  score
0  홍길동   20     90
1  김철수   25     80
2  이영희   23     95

In [2]:
df['age']

0    20
1    25
2    23
Name: age, dtype: int64

In [4]:
type(df['age'])

pandas.Series

In [6]:
df[['name','age']]
type(df[['name','age']])

pandas.DataFrame

In [7]:
df.age

0    20
1    25
2    23
Name: age, dtype: int64

In [8]:
df.loc[:, 'age']

0    20
1    25
2    23
Name: age, dtype: int64

In [9]:
df.loc[:, ['name','age']]

  name  age
0  홍길동   20
1  김철수   25
2  이영희   23

In [10]:
df.iloc[:,1]

0    20
1    25
2    23
Name: age, dtype: int64

In [12]:
df.iloc[:, [0,2]]

  name  score
0  홍길동     90
1  김철수     80
2  이영희     95